| **Kinga Węzka** <BR> kinga.wezka@pw.edu.pl  <BR> Warsaw University of Technology <BR> Faculty Geodesy and Cartography <BR> Plac Politechniki 1 (room 38)<BR> 00-661 Warszawa, POLAND<BR> <A href="https://www.google.com/maps/place/Gmach+G%C5%82%C3%B3wny+Politechniki+Warszawskiej/@52.220656,21.0094422,19z/data=!3m1!4b1!4m5!3m4!1s0x471ecce951c85a19:0x712b0e1503c42b91!8m2!3d52.220656!4d21.0099894"> N 52&ordm; 12' 45&quot; / E 21&ordm; 03' 51&quot;</A></B><BR> | <a rel="license" href="https://www.pw.edu.pl"><img alt="Politechnika Warszawska" style="border-width:0" src="https://www.pw.edu.pl/design/pw/images/znak-pw.png" /></a> |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|

**Informatyka Geodezyjna** (projekt) -- rok akademicki 2020/2021
    
**Prowadzący:** Kinga Węzka, Joanna Kożuchowska 
    
**Projekt 8:** Obliczenia numeryczne z wykorzystaniem biblioteki **NumPy**

**UWAGA: Odpowiedź na każde pytanie powinna znajdować się w oddzielnej komórce poniżej pytania, z podanym numerem pytania**


# Spis treści:

1. [Zad. 1: Tworzenie i modyfikacja tablicy ndarray](#zad1)
2. [Zad. 2: Rozwiązanie układu równań](#zad2)
3. [Zad. 3: Tablice z wartościami NaN ](#zad3)
4. [Zad. 4: Wyszukiwania w tablicy ndarray](#zad4)
5. [Zad. 5: Iteracje po elementach ](#zad5)
6. [Zad. 6: Iteracje po elementach i operacje w pętlach tablicy ndarray](#zad6)



## Zad.1: Tworzenie i modyfikacja tablicy ndarray <a name="zad1"></a>
a) Utwórz tablicę A o wymiarach 8x8 i wypełnij ją dowolnymi wartościami (za pomoca liczb losowych lub innego przypisania wartości, tak, żeby w wierszach występowały różne wartości).

b) Utwórz tablicę B, która będzie zawierała fragment tablicy A -> elementy na przecięciu wybranych 4 wierszy i 4 kolumn.

a) Przypisz nową wartość do B[0, 0]. Wyświetl macierz A. Wyjaśnij uzyskany wynik, podaj rozwiązanie zadania, które pozostawia macierz A bez zmian.

b) Zamień wszystkie wartości 1 występujące w macierzy A na wartość 999.

c) Zamień wszystkie wartości 999 występujące w macierzy A na wartość 99.9.

d) Zapisz tablicę A do pliku tekstowego.

e) Otwórz tablicę przypisując ją do zmiennej C.

f) Policz wartości funkcji sinus dla wszystkich elementów w pierwszym wierszu tablicy C.


In [48]:
import numpy as np
import random

#utworzenie tablicy
A = np.array([random.randint(0, 20) for i in range(64)])
A = A.reshape(8, 8)

A = np.zeros(64)
for i in range(64):
    A[i] = random.randint(0, 20) 

A = A.reshape(8,8)
A

array([[13.,  6.,  4.,  2.,  7.,  0.,  1.,  1.],
       [16., 12.,  0.,  1.,  3., 14.,  1., 19.],
       [20., 18.,  7.,  9., 13.,  4., 16.,  4.],
       [ 9.,  8., 13., 16., 15.,  0.,  1., 16.],
       [ 9., 15., 11.,  6.,  5., 19.,  3.,  7.],
       [ 5., 19.,  5.,  7., 11., 15., 13., 11.],
       [17.,  3.,  3., 18., 16., 20., 11.,  7.],
       [13., 14., 11.,  0.,  2.,  2.,  6., 17.]])

In [20]:
B = A[1:5, 5:] # przypisanie tworzy referencje - tablica A będzie modyfikowana
B[0, 0] = 3
print(A)

B = A[1:5, 5:].copy() # utworzenie kopi - tablica A nie będzie modyfikowana
print(B

[[ 7. 18. 11.  5. 13. 14. 11.  3.]
 [20. 12. 16.  4. 10.  3. 13. 20.]
 [17. 20. 15. 16. 16. 19. 18.  4.]
 [ 9. 14. 14. 15.  7. 18.  1.  1.]
 [ 6. 10.  4.  6.  0.  6. 12.  6.]
 [ 0.  3. 13. 16.  1. 13.  5. 16.]
 [14. 17.  0.  2.  1. 10. 20.  4.]
 [17.  0.  2. 11. 10.  9. 10.  4.]]
[[ 3. 13. 20.]
 [19. 18.  4.]
 [18.  1.  1.]
 [ 6. 12.  6.]]


In [ ]:
mask = A == 1 # tablica wartości True/False dla warunku gdzie A == 1
print(mask)
A[mask] = 999
print(A)

B = np.array(A, dtype=np.float64)
mask = B == 999 # tablica wartości True/False dla warunku gdzie B ==99.9
print(mask)
B[mask] = 99.9
print(B)

In [ ]:
# zapis: https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.savetxt.html
np.savetxt("myarray.txt", b1, delimiter=',', fmt = '%10.2f', header = 'jakis naglowek')

# odczyt: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.genfromtxt.html
np.genfromtxt("myarray.txt", delimiter=',', skip_header = 1 , usecols =(5, 4, 3, 1) )

In [57]:
s = np.std(A[:, 1]) 
s = np.min(A[:, 1]) 
print(A)
a = np.full((8,1), 100)
b = A[:, 1].reshape(8,1)

print(b.shape, a.shape)

a + 

[[13.  6.  4.  2.  7.  0.  1.  1.]
 [16. 12.  0.  1.  3. 14.  1. 19.]
 [20. 18.  7.  9. 13.  4. 16.  4.]
 [ 9.  8. 13. 16. 15.  0.  1. 16.]
 [ 9. 15. 11.  6.  5. 19.  3.  7.]
 [ 5. 19.  5.  7. 11. 15. 13. 11.]
 [17.  3.  3. 18. 16. 20. 11.  7.]
 [13. 14. 11.  0.  2.  2.  6. 17.]]
(8, 1) (8, 1)


array([[13.,  6.,  4.,  2.,  7.,  0.,  1.,  1.],
       [16., 12.,  0.,  1.,  3., 14.,  1., 19.],
       [20., 18.,  7.,  9., 13.,  4., 16.,  4.],
       [ 9.,  8., 13., 16., 15.,  0.,  1., 16.],
       [ 9., 15., 11.,  6.,  5., 19.,  3.,  7.],
       [ 5., 19.,  5.,  7., 11., 15., 13., 11.],
       [17.,  3.,  3., 18., 16., 20., 11.,  7.],
       [13., 14., 11.,  0.,  2.,  2.,  6., 17.]])

## Zad. 2: Rozwiązanie układu równań <a name="zad2"></a>
Korzystając z rachunku macierzowego rozwiąż układ równań:

$$ \begin{matrix}
2a &+  b  &+  c &= 4  \\
a  &+  3b &+ 2c &= 5 \\
a  &      &   &= 6 
\end{matrix}$$


A - macierz współrzczynników przy niewiadomych:
$$A = \begin{bmatrix} 2 & 1 & 1 \\ 1 & 3 & 2 \\ 1 & 0 & 0\end{bmatrix}$$

B - macierz wyników:
$$B = \begin{bmatrix} 4\\ 5 \\ 6 \end{bmatrix}$$

x - macierz niewiadomych:
$$x = \begin{bmatrix} a\\ b \\ c \end{bmatrix}$$



Zapis równania liniowego w postaci macierzowej zapisać w następujący sposób:
$$Ax = B $$

Aby rozwiązać powyższe równanie należy wyznaczyć wektor x (wektor niewiadomych), musimy odwrotność macierzy Apomnożyć przez B następująco:

$$ x = A^{-1}B $$

Do rozwiązania zadania wykorzystaj:

a) tablice ndarray

b) zmienne typu matrix

c) sprawdź uzyskane rozwiązanie za pomocą odpowiedniej metody z modułu np.linalg 

odp.  a =  6,  b = 15, c =-23

In [1]:
import numpy as np
import numpy.linalg

from numpy.linalg import inv 

# zdefiniowanie tablicy A, A - macierz współrzczynników przy niewiadomych:
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]]) 

# zdefiniowanie tablicy  B, B - macierz wyników:
B = np.array([[4], [5], [6]]) 

# x - macierz niewiadomych:

# metoda 1. działania na tablicach ndarray
x = inv(A).dot(B) 
print('--------------------- metoda 1:\n', x)

# metoda 2. działania na tablicach matrix: https://docs.scipy.org/doc/numpy/reference/routines.matlib.html
# metody macierzy: https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html#numpy.matrix
Am = np.matrix(A) # konwersja ndarray do matrix
Bm = np.matrix(B) # konwersja ndarray do matrix
x  =   Am.I * B
print('--------------------- metoda 2:\n', x)



# metoda 3: wykorzystanie metody - zakaz używania tego typu metod w tym semestrze !!! :P
x = np.linalg.solve(A, B)
print('---------------------metoda 3:\n', x)

--------------------- metoda 1:
 [[  6.]
 [ 15.]
 [-23.]]
--------------------- metoda 2:
 [[  6.]
 [ 15.]
 [-23.]]
---------------------metoda 3:
 [[  6.]
 [ 15.]
 [-23.]]


## Zad. 3: Tablice z wartościami NaN  <a name="zad3"></a>

+ a) Zdefinuj tablicę o wymiarach (4x4) zawierająca wartości liczb całkowitych w zakresie od 0 do 20.
+ b) Wyszukaj wartości większe od 10 i zamień je na wartość nan. 
+ c) Policz średnią dla wszystkich elementów 3ciej kolumny.

**Pomoc**: Zerknij do notebooka **help_numpy.ipynb**

In [24]:
import numpy as np
import random

# a) utworzenie tablicy
A = np.array([random.randint(0, 15) for i in range(16)], dtype=np.float64)
A = A.reshape(4, 4)

# b
mask = A > 10 # tablica wartości True/False dla warunku gdzie A == 1
print(mask)

print(A.dtype)
A[mask] = np.nan
print(A)

# c = 

[[ True False False False]
 [ True False False  True]
 [ True False False  True]
 [False  True  True False]]
float64
[[nan  1.  7.  6.]
 [nan  6.  3. nan]
 [nan  3.  3. nan]
 [ 8. nan nan  9.]]


## Zad. 4: Wyszukiwania w tablicy ndarray <a name="zad4"></a>
Poniższa tablica zawiera wartości zaisane w kolumnach odpowiednio: col1 = epoka, col2 = numer satelity, col3 = PDOP, col4 = HDOP.

- a) Znajdź w tablicy wiersze w których wartość kolumny 3 jest większa od 2

- b) Znajdź w tablicy wiersze w których wartość kolumny 4 jest większa od 8. Nastepnie zamień wartości w kolumnie 4 większe od 8 wartością `None`

- c) Podziel poniższą tablicę na trzy tablice każda z tablic ma zawierać wiersze jedynie dla tej samej epoki.

In [1]:
import numpy as np
A = np.array([
    [1, 12,  2.2, 2.1],
    [1,  2,  3.1, 3.3],
    [1, 19,  1.8, 3.5],
    [1, 22,  2.1, 2.2],
    [1, 31,  5.1, 8.2],
    [2, 12,  3.5, 1.2],
    [2,  2,  3.1, 4.6],
    [2, 19,  1.3, 3.2],
    [2, 22,  6.1, 3.2],
    [2, 31,  7.1, 8.2],
    [2, 14,  2.1, 1.2],
    [3, 12,  3.2, 2.3],
    [3, 12,  4.1, 8.2],
    [3, 12,  3.1, 3.2]])


print('----------------- solution a: ---------------------------')
b = A[A[:,2]>2]
print(b)


print('----------------- solution b: ---------------------------')
A[A[:,3]>8,3] = None
print(A)    

----------------- solution a: ---------------------------
[[ 1.  12.   2.2  2.1]
 [ 1.   2.   3.1  3.3]
 [ 1.  22.   2.1  2.2]
 [ 1.  31.   5.1  8.2]
 [ 2.  12.   3.5  1.2]
 [ 2.   2.   3.1  4.6]
 [ 2.  22.   6.1  3.2]
 [ 2.  31.   7.1  8.2]
 [ 2.  14.   2.1  1.2]
 [ 3.  12.   3.2  2.3]
 [ 3.  12.   4.1  8.2]
 [ 3.  12.   3.1  3.2]]
----------------- solution b: ---------------------------
[[ 1.  12.   2.2  2.1]
 [ 1.   2.   3.1  3.3]
 [ 1.  19.   1.8  3.5]
 [ 1.  22.   2.1  2.2]
 [ 1.  31.   5.1  nan]
 [ 2.  12.   3.5  1.2]
 [ 2.   2.   3.1  4.6]
 [ 2.  19.   1.3  3.2]
 [ 2.  22.   6.1  3.2]
 [ 2.  31.   7.1  nan]
 [ 2.  14.   2.1  1.2]
 [ 3.  12.   3.2  2.3]
 [ 3.  12.   4.1  nan]
 [ 3.  12.   3.1  3.2]]


Tablica B: 
 [[1.  7.  2.2 2.1]
 [2.  1.  3.5 1.2]
 [1.  2.  3.1 3.3]]


In [96]:
print('----------------- solution c: ---------------------------')
# determine where the data "splits" shoule be
col1 = A[:, 0]
print(col1)
print(np.roll(col1,1)) # wykonuje przesunicie kolejnych elementów o 1

diff = col1 - np.roll(col1,1)
idxs = np.where(diff>0)[0] # indexy (numery wiersza podziału tablicy)

# ------ metoda 1 podziału:
n = np.split(A, list(idxs))
print(n)

# ------ metoda 2 podziału: pętla dzięląca tablice "splits"
strts = idxs
stops = list(idxs[1:])+[None]
groups = [A[strt:stop] for strt,stop in zip(strts,stops)]

----------------- solution c: ---------------------------
[ 1.  1.  1.  1. nan  2.  2.  2.  2. nan  2.  3. nan  3.]
[ 3.  1.  1.  1.  1. nan  2.  2.  2.  2. nan  2.  3. nan]
[array([[ 1. , 12. ,  2.2,  2.1],
       [ 1. ,  2. ,  3.1,  3.3],
       [ 1. , 19. ,  1.8,  3.5],
       [ 1. , 22. ,  2.1,  2.2],
       [ nan,  nan,  nan,  nan],
       [ 2. , 12. ,  3.5,  1.2],
       [ 2. ,  2. ,  3.1,  4.6],
       [ 2. , 19. ,  1.3,  3.2],
       [ 2. , 22. ,  6.1,  3.2],
       [ nan,  nan,  nan,  nan],
       [ 2. , 14. ,  2.1,  1.2]]), array([[ 3. , 12. ,  3.2,  2.3],
       [ nan,  nan,  nan,  nan],
       [ 3. , 12. ,  3.1,  3.2]])]


/home/kinga/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in greater
  


## Zad. 5: Iteracje po elementach tablicy ndarray <a name="zad5"></a>
Korzystając z pętli zagnieżdżonych, zaimplementuj mnożenie macierzy korzystając z jego definicji.

In [105]:
# Program to multiply two matrices using nested loops
# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]
        
for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


## Zad. 6: Iteracje po elementach i operacje w pętlach tablicy ndarray <a name="zad6"></a>
Majac daną tablicę A oraz korzystając z pętli wykonaj następujące działania, wyniki zapisz do nowej tablicy B:


- policz sumę elementów w każdym wierszu znajdujących się w  drugiej i trzeciej kolumnie A oraz wstaw wynik do odpowiedniego wiersza w kolumnie czwartej tablicy B.


- w pierwszej kolumnie tablicy B wstaw numery kolejnych wierszy;

- w drugiej kolumnie tablicy B wstaw sumę elementów wiersza tablicy A;

- w trzeciej kolumnie tablicy B, wstaw największa wartość z wiersza tablicy A.


In [19]:
import numpy as np

A = np.array([
    [1, 12,  2.2, 2.1],
    [1,  2,  3.1, 3.3],
    [1, 19,  1.8, 3.5],
    [1, 22,  2.1, 2.2],
    [1, 31,  5.1, 8.2],
    [2, 12,  3.5, 1.2],
    [2,  2,  3.1, 4.6],
    [2, 19,  1.3, 3.2],
    [2, 22,  6.1, 3.2],
    [2, 31,  7.1, 8.2],
    [2, 14,  2.1, 1.2],
    [3, 12,  3.2, 2.3],
    [3, 12,  4.1, 8.2],
    [3, 12,  3.1, 3.2]])

B = np.zeros(A.shape)

# a
for i in range(A.shape[0]):
    #a
    B[i, 3] = A[i, 1] + A[i, 2]
    #b
    B[i, 0] = i
    # c
    B[i, 1] = A[i, :].sum()
    # d
    B[i, 2] = A[i, :].max()
print(B)

[[ 0.  17.3 12.  14.2]
 [ 1.   9.4  3.3  5.1]
 [ 2.  25.3 19.  20.8]
 [ 3.  27.3 22.  24.1]
 [ 4.  45.3 31.  36.1]
 [ 5.  18.7 12.  15.5]
 [ 6.  11.7  4.6  5.1]
 [ 7.  25.5 19.  20.3]
 [ 8.  33.3 22.  28.1]
 [ 9.  48.3 31.  38.1]
 [10.  19.3 14.  16.1]
 [11.  20.5 12.  15.2]
 [12.  27.3 12.  16.1]
 [13.  21.3 12.  15.1]]
